### ISSUE TITLE
P3 wont install Fortify

### ISSUE THREAD

**Issue by traveler9878** [susanBuck/e15-spring23#36] opened 2023-05-06 04:40 UTC
```
root@hes:/var/www/e15/p3# composer update 
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v10.0.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.0.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.0.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.2.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.4.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.4.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.5.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.5.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.6.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.6.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.6.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.7.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.7.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.8.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.9.0 (conflict analysis result)
    - spatie/laravel-ignition[1.5.0, ..., 1.6.4] require illuminate/support ^8.77|^9.27 -> satisfiable by illuminate/support[v8.77.0, ..., v8.83.27, v9.27.0, ..., v9.52.7].
    - spatie/laravel-ignition[1.0.0, ..., 1.4.1] require illuminate/support ^8.77|^9.0 -> satisfiable by illuminate/support[v8.77.0, ..., v8.83.27, v9.0.0, ..., v9.52.7].
    - Only one of these can be installed: illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.7, v10.0.0, ..., v10.9.0], laravel/framework[v10.0.0, ..., v10.9.0]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^10 -> satisfiable by laravel/framework[v10.0.0, ..., v10.9.0].
    - Root composer.json requires spatie/laravel-ignition ^1.0 -> satisfiable by spatie/laravel-ignition[1.0.0, ..., 1.6.4].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

**Comment by traveler9878** [comment] 2023-05-06 04:41
First Attempt:
```
root@hes:/var/www/e15/p3# composer require laravel/fortify
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^1.17 for laravel/fortify
./composer.json has been updated
Running composer update laravel/fortify
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/framework ^10, found laravel/framework[v10.0.0, ..., v10.9.0] but the package is fixed to v9.52.7 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel/fortify:*" to figure out if any version is installable, or "composer require laravel/fortify:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by traveler9878** [comment] 2023-05-06 04:44
Same problem with bookmark:

```
root@hes:/var/www/e15/bookmark# composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/fortify ^2.1, found laravel/fortify[dev-master, 2.x-dev (alias of dev-master)] but it does not match your minimum-stability.
  Problem 2
    - Conclusion: don't install laravel/framework v10.0.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.0.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.0.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.2.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.4.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.4.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.5.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.5.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.6.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.6.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.6.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.7.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.7.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.8.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.9.0 (conflict analysis result)
    - spatie/laravel-ignition[1.5.0, ..., 1.6.4] require illuminate/support ^8.77|^9.27 -> satisfiable by illuminate/support[v8.77.0, ..., v8.83.27, v9.27.0, ..., v9.52.7].
    - spatie/laravel-ignition[1.0.0, ..., 1.4.1] require illuminate/support ^8.77|^9.0 -> satisfiable by illuminate/support[v8.77.0, ..., v8.83.27, v9.0.0, ..., v9.52.7].
    - Only one of these can be installed: illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.7, v10.0.0, ..., v10.9.0], laravel/framework[v10.0.0, ..., v10.9.0]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^10 -> satisfiable by laravel/framework[v10.0.0, ..., v10.9.0].
    - Root composer.json requires spatie/laravel-ignition ^1.0 -> satisfiable by spatie/laravel-ignition[1.0.0, ..., 1.6.4].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
root@hes:/var/www/e15/bookmark# 
```

**Comment by traveler9878** [comment] 2023-05-06 15:59
perhaps I missed it but I removed this from composer.json in bookmark and set laravel to require 10.0.0 and it worked:
```
        "spatie/laravel-ignition": "^1.0"
```
Trying it on p3 now

**Comment by traveler9878** [comment] 2023-05-06 17:48
This fix breaks the authentication because the fortify auth uses the removed tool

**Comment by traveler9878** [comment] 2023-05-06 18:20
https://github.com/laravel/framework/discussions/46124

**Comment by traveler9878** [comment] 2023-05-06 18:36
So, I deleted the composer.lock file and vendors folder and set laravel to version 9.* and added back the removed dependency above and that passed a composer install without failures, but nginx is still giving me a 403 or 404 on my projects...

**Comment by susanBuck** [comment] 2023-05-06 19:23
Recreating/testing on my end now. Will reply shortly.

**Comment by susanBuck** [comment] 2023-05-06 19:43
In your site config for P3, the `root` is pointing to `/var/www/e15/p3/`, but it should be `/var/www/e15/p3/public`

```
server {

    listen 80;
    server_name e15p3.davidcurtis.me;
    root /var/www/e15/p3/;
    
    [...etc...]
```

Update that and restart your server.

**Comment by susanBuck** [comment] 2023-05-06 19:46
Rewinding back to the Laravel 9 vs 10 and Fortify issue - you can either proceed forward since you got it working with version 9, or if you want I can log into your server and attempt the upgrade and report back what I find out. It'll be easier for me to run through the process and see exactly what is going on vs. track what happened from the above output. Especially because the above output references something a "partial update" so not sure exactly what's going on there.

Let me know which you prefer, and when a good window for me to try it would be - I don't want to be in your server/code making changes at the same time you're working. : )

**Comment by traveler9878** [comment] 2023-05-06 20:36
I definitely wouldn't say I got it working, if you can log in and check it out that will be great.  I have another server I registered as part of my capstone, it's on Aero-NEO.com on digital ocean, I was about to start building fresh on that one... I put your cert on the access list there too but I haven't built anything there.  If something turns out to be corrupt it's a last resort.

**Comment by traveler9878** [comment] 2023-05-06 20:37
I can't work on it in it's current state except to troubleshoot the http layer and composer compatibility problems

**Comment by susanBuck** [comment] 2023-05-06 20:43
Ok going to log in now and troubleshoot. Will let you know when I'm done.

**Comment by traveler9878** [comment] 2023-05-06 20:47
thanks

**Comment by susanBuck** [comment] 2023-05-06 21:25
**Here are my notes on what I did on your server to get everything working:**

Corrected `root /var/www/e15/p3` to `root /var/www/e15/p3/public;` in `/etc/nginx/sites-available/hes`. Restarted server.

Application would now load but routing was not working.

Looking closer at the server config - see p3 was set up with the [simpler server configs we were using earlier in the semester](https://hesweb.dev/e15/notes/infrastructure/subdomains#subdomains). Updated with the [Laravel-specific configs necessary for routing to work](https://hesweb.dev/e15/notes/laravel/new-laravel-app#configure-subdomain).

Routing was now working; attempted to visit http://e15p3.davidcurtis.me/login but got error `View [includes.error-field] not found.` 

Put in missing view file, was able to load login page and log in.

Confirmed registration was also working.

Now that was everything was working, proceeded forward with upgrade

Following [Laravel upgrade guide](https://laravel.com/docs/10.x/upgrade), updated composer.json as follows:
+ laravel/framework 9.0 → 10.0
+ laravel/sanctum was already at 3.2
+ doctrine/dbal - not applicable
+ laravel/passport - not applicable

Ran `composer update`; completed without error.

Tested site - loaded without errors; tested login was still functioning. 

So as of this writing your P3 is functioning and running Laravel 10. I did remove the SSL configs from your site config file just to get it working on regular http first. Let me loop back with you on Monday and we can tackle the SSL issue since it's not essential for right now.

**Comment by traveler9878** [comment] 2023-05-06 21:31
Thanks!

**Comment by susanBuck** [comment] 2023-05-08 03:05
I'm going to close this thread; will follow-up on the SSL settings in issue #37.

**Closed as completed by susanBuck** 2023-05-08 03:05 UTC

**Comment by traveler9878** [comment] 2023-05-08 03:06
Thanks
